using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.IO;
using System.Linq;
using System.Text;

public static class SourceProductionContextExtensions
{
    public static void AddAdditionalFile(
        this SourceProductionContext context,
        string hintName,
        SourceText text)
    {
        context.AddSource(hintName.Replace('.', '_') + ".g.cs",
            SourceText.From(
$@"// <auto-generated/>
// This file embeds: {hintName}
// Generator workaround for non-CS file output.

namespace GeneratedXaml 
{{
    internal static class {Sanitize(hintName)}
    {{
        public const string Content = @""{Escape(text.ToString())}"";
    }}
}}", Encoding.UTF8));
    }

    private static string Escape(string value) =>
        value.Replace("\"", "\"\"");

    private static string Sanitize(string value) =>
        new string(value.Where(char.IsLetterOrDigit).ToArray());

}