<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<!-- Embed the font so WPF can find it -->
		<Resource Include="Assets\SegoeFluent.ttf" Pack="true" PackagePath="Assets\" />

		<!-- Embed the XAML for icons -->
		<Resource Include="FluentIcons.xaml" Pack="true" PackagePath="Assets\" />
	</ItemGroup>

</Project>