<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
	  <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Future.UX.FluentIcons</PackageId>
    <Version>0.1.8</Version>
    <Authors>Rich</Authors>
    <Company>Future.UX</Company>
    <Description>A collection of Fluent Icons for use in .NET applications.</Description>
    <PackageTags>Fluent Icons Pack .NET</PackageTags>

    <RepositoryUrl>https://github.com/rharrison891/Future.UX</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <!-- Embed the font inside the DLL as a WPF resource -->
    <Resource Include="Assets\SegoeFluent.ttf" />

    <!-- Embed the XAML dictionary -->
    <Resource Include="FluentIcons.xaml" />
  </ItemGroup>

</Project>