<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<PackageId>Future.UX.MVVM</PackageId>
		<Version>0.1.1</Version>
		<Authors>Rich</Authors>
		<Company>Future.UX</Company>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>Lightweight MVVM helpers for WPF: RelayCommand, AsyncRelayCommand.</Description>
		<PackageTags>mvvm wpf relaycommand async commands</PackageTags>

		<RepositoryUrl>https://github.com/rharrison891/Future.UX</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\"/>
	</ItemGroup>
</Project>
