<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Future.UX.MVVM\Future.UX.MVVM.csproj" />
		<ProjectReference Include="..\Future.UX.SourceGenerators\Future.UX.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<!--<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>-->
</Project>
